app/assets/javascripts/products.coffee
app/assets/javascripts/users.coffee
app/assets/stylesheets/_reset.scss
app/assets/stylesheets/products.scss
app/assets/stylesheets/users.scss
app/controllers/products_controller.rb
app/controllers/users_controller.rb
app/helpers/products_helper.rb
app/helpers/users_helper.rb
test/controllers/products_controller_test.rb
test/controllers/users_controller_test.rb

追加事項
・asset/stylesheetフォルダに_reset.cssを追加
・users controllerとproducts controllerの作成/追加
・CSSの統一
・usersとproductsのコントローラは必須項目なので先に作成

reset.cssとcontrollerの追加

---

app/assets/stylesheets/_users_sms_confirmation.scss
app/controllers/users_controller.rb
app/views/users/sms_authentication.html.haml
config/routes.rb

ユーザー登録ページ 4ページ目のマークアップを完了した。
以下がオリジナル

ユーザー新規登録ページのマークアップ(4/7ページ目)

---

Gemfile.lock
README.md

下記ファイルを更新
・README.md
DB設計内容をREADMEファイルに記載することで、モデルの作成に利用するため。

DB設計内容をREADMEファイルに追記

---

app/assets/stylesheets/_mypage_profile.scss
app/views/users/mypage_profile.html.haml

what
profile_mypageの修正
side bar, header, footerのrender
background-imageの挿入
その他微調整、margin等
作成物
本物

fixed profile-page view

---

app/assets/stylesheets/_mypage.scss
app/assets/stylesheets/_mypage_profile.scss
app/views/users/mypage.html.haml
app/views/users/mypage_profile.html.haml

sidebar, header, footerのrender
クラスの名前変更(mypage, mypage_profile)
その他微調整(margin等）
font-awsomeはまだしていないです。
タブの切り替えはできません。
作成物
本物

mypage-fix 1

---

app/assets/stylesheets/_syuppin.scss
app/assets/stylesheets/_toppage.scss

toppage-syuusei

---

app/assets/stylesheets/_products_confirm.scss
app/views/products/confirm.html.haml

商品登録確認ページの微修正
大枠に影響は無いため、即マージします。

ビュー&スタイルの微修正

---

app/assets/stylesheets/_footer.scss
app/assets/stylesheets/_toppage.scss
app/views/products/toppage.html.haml

toppagesyuusei

---

app/views/products/toppage.html.haml
app/views/users/card.html.haml
app/views/users/card_create.html.haml
app/views/users/mypage.html.haml
app/views/users/profile.html.haml
app/views/users/signup.html.haml
app/views/users/syuppin.html.haml

部分テンプレートのディレクトリ変更によるリンク切れを修正しました。

部分テンプレートのディレクトリ変更によるリンク切れ修正

---

Gemfile
Gemfile.lock
app/uploaders/image_uploader.rb

下記、gemをインストール。
fog-aws
carrierwave
mini_magic
#why
S3環境構築のため、必要なgemをインストール。

fog-aws/carrierwave/mini_magickの追加

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_header.scss
app/assets/stylesheets/application.scss
app/views/shared/_header.html.haml

- gem 'font-awesome-sass' を導入
- ヘッダーに試験的に導入

font-awesome-sassの導入、およびヘッダーへの試験的導入

---

app/views/products/toppage.html.haml
app/views/users/syuppin.html.haml

/WHAT
トップページと出品ページのビューを作りました。
/WHY
今後の実装の土台となるため。

トップページと出品ページについてのコードレビュー

---

.gitignore
Gemfile
app/uploaders/image_uploader.rb
config/deploy.rb
config/initializers/carrierwave.rb
config/secrets.yml

下記、ファイルを編集。
・image_uploader.rb
・deploy.rb
・carrierwave.rb
・本番環境であるAWS S3とローカル開発環境を条件分岐。
・画像保存環境の構築。

AWS S3環境の構築

---

app/assets/stylesheets/_header.scss
app/assets/stylesheets/_products_detail.scss

what
headerのそれぞれの位置の微調整
scssの不必要なプロパティを削除
本物
作成物

fix-header

---

app/assets/stylesheets/_sell.scss
app/assets/stylesheets/application.scss
app/controllers/users_controller.rb
app/views/users/sell.html.haml
config/routes.rb

/what
ビューと出品ページの名前を直しました。
/why
出品ページの名前をわかりやすくするため。
ビューが崩れていたから。

出品ページ直しました

---

README.md

README.mdファイルにDB設計を記載。
モデル作成時にテーブルを利用するため。

READMEファイルの記載

---

Gemfile
Gemfile.lock
app/models/user.rb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20190810022949_devise_create_users.rb
db/schema.rb
test/fixtures/users.yml
test/models/user_test.rb

Userモデルを作成した
##Why 
各種機能の実装において、Userモデルが必要不可欠であるため。
- gem 'devise' をインストール
- Userモデルを作成
- デフォルトのカラム(email, password)のみでdb:migrateを実行
- マイグレーションファイルを作成し、add columnsでUsersテーブルにカラムを追加
- User登録機能の実装

ユーザーモデルの作成

---

app/assets/javascripts/sell.js
app/assets/stylesheets/_sell.scss
app/views/products/sell.html.haml

/what
出品ページのフォームに文字を入力できるようにした。
また、写真をJSを使い、ドラッグ＆ドロップまたはクリックで読み込めるようにした（文字データのみ）
/why
これから実装する出品ページのサーバサイドを作るため

出品ページのフォームに文字を書く＆写真の登録その①

---

app/assets/stylesheets/_users_login.scss
app/controllers/users_controller.rb
app/views/shared/_l-side.html.haml
app/views/users/login.html.haml
app/views/users/mypage.html.haml

既存ユーザーの、メールアドレスでのログインを可能にした。
それに伴い、一部のビューやリンクについても修正した。
必須の機能であるため。
- テストコードは未実装。今後、「ログインしているユーザーがサインアウト出来ること」ならびに「ログインできるユーザーがサインインできること」の2点に関しては、コントローラの単体テストor統合テストで自動テスト化する予定です。

[WIP] メールアドレスでのログインを可能に

---

app/controllers/cards_controller.rb

- Secretキーの環境変数への置き換え
- ローカルおよび本番環境でのbash_profileの記述

本番環境でクレカ情報を登録可能とした

---

app/assets/stylesheets/_header.scss
app/assets/stylesheets/_toppage.scss
app/controllers/cards_controller.rb
app/controllers/products_controller.rb
app/views/products/toppage.html.haml

/what
トップページのアイテムをカラムに書いた詳細ページに飛ばす
/why
リンクをつけて、クリック後詳細ページに飛ばすため

トップページのアイテムを詳細ページに飛ばす

---

app/assets/stylesheets/_footer.scss
app/views/shared/_selling_btn.html.haml

/what
出品のカメラボタンを押すと、商品出品ページに飛ぶようにしました
/why
出品ページに飛ばせるため

出品のカメラボタンを押すと、商品出品ページに飛ぶ

---

app/controllers/products_controller.rb
app/views/products/thirdcategory.js.erb

product.rbのcreateアクション下に、logger.debug @product.errors.inspectを追記
本番環境における投稿テストのエラーログ出力のため。

【WIP】本番環境におけるloggerの追加

---

app/assets/stylesheets/_item.scss
app/assets/stylesheets/_l.scss
app/controllers/products_controller.rb
app/views/products/show.html.haml
app/views/shared/_header.html.haml
app/views/users/identification.html.haml
spec/controllers/products_controller_spec.rb
spec/factories/brands.rb
spec/factories/brands_categories.rb
spec/factories/first_categories.rb
spec/factories/products.rb
spec/features/products_spec.rb

what
検索機能のテスト
why
検索機能検証
テスト内容
１、プロダクトA、プロダクトB、プロダクトCを作成
2、検索フォームにAを入力し検索ボタンを押す
2、検索フォームにBを入力し検索ボタンを押す
2、検索フォームにCを入力し検索ボタンを押す
2、検索フォームにプロダクトを入力し検索ボタンを押す

Search test

---

app/assets/stylesheets/_l.scss
app/views/products/search.html.haml

check-box-view

---

app/assets/stylesheets/_index.scss
app/controllers/products_controller.rb

エラー修正（SOLDタグの位置調整＆購入機能の調整）

---

app/controllers/products_controller.rb
app/views/products/index.html.haml

トップページでブランドごとに商品を表示
